DROP DATABASE IF EXISTS tix;
CREATE DATABASE tix;
USE tix;

DROP TABLE IF EXISTS User;
CREATE TABLE User(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(31) UNIQUE NOT NULL,
  password VARCHAR(31) NOT NULL
);

DROP TABLE IF EXISTS Avatar;
CREATE TABLE Avatar(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  color INT NOT NULL ,
  login VARCHAR(31) UNIQUE NOT NULL,
  FOREIGN KEY (user_id) REFERENCES User(id)
);
