DROP DATABASE IF EXISTS tix;
CREATE DATABASE tix;
USE tix;

DROP TABLE IF EXISTS Avatar;
CREATE TABLE Avatar(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  color INT NOT NULL ,
  login VARCHAR(31) UNIQUE NOT NULL
);
