DROP DATABASE IF EXISTS tix;
CREATE DATABASE tix;
USE tix;

DROP TABLE IF EXISTS User;
CREATE TABLE User(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  color INT NOT NULL ,
  login VARCHAR(31) UNICODE NOT NULL
);
